version: 2
jobs:

  deployment:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - run: aws s3 ls s3://pinglinh.com

workflows:
  version: 2
  build_and_test:
    jobs:
      - deployment
